services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php-api
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/html/api
      - ./src:/var/www/html/src
    env_file:
      - .env.development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - path: ./api
          target: /var/www/html/api
          action: sync+restart

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: n2oliver-react
    working_dir: /var/www/html/
    ports:
      - "3000:3000"
    volumes:
      - ./package.json:/var/www/html/src/package.json
      - ./public:/var/www/html/src/public
      - /var/www/html/src/node_modules
    env_file:
      - .env.development
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped
    develop:
      watch:
        - path: ./src
          target: /var/www/html/src
          action: sync+restart
