services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
    env_file:
      - .env.development
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: n2oliver-react
    working_dir: /src
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
      - /src/node_modules
    env_file:
      - .env.development
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped
    develop:
      watch:
        - path: . # Path to monitor for changes
          action: rebuild # Action to take: rebuild the image and recreate the container
        - path: ./package.json # Example for specific file requiring rebuild
          action: rebuild