services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php-api
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html/api
    env_file:
      - .env.development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react-app
    working_dir: /src
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
      - /src/node_modules
    env_file:
      - .env.development
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped