FROM node:22

WORKDIR /

COPY package*.json ./var/www/html/
COPY ./src/ /var/www/html/src/
COPY ./public/ /var/www/html/public/

RUN cd ./var/www/html/ && npm install

EXPOSE 3000

CMD ["npm", "start"]